return {
  ["builders"] = "wk7-a4-ca143d92-7e34-569b-b008-1f69817ffff5",
  ["id"] = "3I2vPS4a4S5LW5rLX3ns7kInGPr",
  ["parent"] = "3HyRcrR35sYRwZl3guddvOBhFoK",
  ["pr"] = 1567,
  ["repo"] = "cosmic-lua/cosmic",
  ["resolution"] = "completed",
  ["title"] = "coverage report should derive its exclusions from .cosmicignore",
  ["verdict"] = "accept",
  ["verdict_head"] = "39bba393451faa5cd74cc43fcf9ce0ae3d8c2874",
  ["verdict_spec"] = "42751b16d00665ccbe768b87768d3a8309ed03cbdfd1c8ddd0d74052884c3e84",
}
