return {
  ["blocked_by"] = "3I7LBrUNPB3uYAcUtrihQEJFNoz 3I7LDODdkyLXM4vLvGvDHlOpmtf 3I7LEsGv553b26TPxbtbVSimkZ5 3I7LGcLaE6xqOwmNxcdBvRtT6Ft",
  ["builders"] = "orch9-hold-6 orch9-build-net",
  ["id"] = "3I7LMwgCMPZ6cUQbMe4mqccNQnm",
  ["parent"] = "3I1IfJ228vyPoO9rhbHhc6RjxJB",
  ["pr"] = 1596,
  ["repo"] = "cosmic-lua/cosmic",
  ["resolution"] = "completed",
  ["title"] = "sandbox: net section — per-port TCP policy via landlock ABI 4 (R7)",
  ["verdict"] = "accept",
  ["verdict_head"] = "86c56d5a9287ef50e89ff5bb5900fc991d8f481a",
  ["verdict_spec"] = "d0ed1c3c0ad776398c1460e1ce0ffbf7c603122ab307fb7a215b9bc6ebe6c0bd",
}
