return {
  ["builders"] = "wk5-a3-ca143d92-7e34-569b-b008-1f69817ffff5 wk6-b2-ca143d92-7e34-569b-b008-1f69817ffff5",
  ["id"] = "3IcLoDKfOhfIXgtXQXPNgyLS9wQ",
  ["parent"] = "3IOCdooEOElQSPH42nr5xOrAQVn",
  ["pr"] = 1563,
  ["repo"] = "cosmic-lua/cosmic",
  ["resolution"] = "completed",
  ["speccers"] = "orchestrator-w18 ca143d92-7e34-569b-b008-1f69817ffff5",
  ["title"] = "cosmic/format/init_test.tl has no test_* functions at all: it will pass the migration's exit test as 'empty' while defeating its point",
  ["verdict"] = "accept",
  ["verdict_head"] = "586cee587d692848293ddeda0816287784fde9f2",
  ["verdict_spec"] = "f45fe1ee6deed5da5ad9fa32db75329a0cf27a4d307d9d85ebe3499066cf9267",
}
