return {
  ["beats"] = "3IYMMznaIOzbNMRIgbb92BFalGR",
  ["builders"] = "wave2-2-naUv",
  ["id"] = "3IhTIWdIKWR79voRm2NnaUvcQdf",
  ["parent"] = "3HyRdY4sPAYZ6xkwrXCh5BnsH7B",
  ["pr"] = 1601,
  ["repo"] = "cosmic-lua/cosmic",
  ["resolution"] = "completed",
  ["speccers"] = "d6d4a5ca-5feb-579c-b294-e39c72bf3099",
  ["title"] = "cosmic/surface_test.tl classifies any embedded directory as a public module by is_dir() alone, disagreeing with _build/public_surface.tl's init.tl check",
  ["verdict"] = "accept",
  ["verdict_head"] = "fc7aed6f6e6b9c38f63a8ea64620ccf8186b370c",
  ["verdict_spec"] = "76ed981e96fa653a68c07ed4201a459530e554424b86a7eb55b4ecdef33723c3",
}
