return {
  ["beats"] = "3I7LKuM2tyxxJ6ZTgYVX8RoI6Dl",
  ["builders"] = "wave2-1-dDNs",
  ["id"] = "3IhTfAF54yco7fp3y5vdDNstnLQ",
  ["parent"] = "3I1IfJ228vyPoO9rhbHhc6RjxJB",
  ["pr"] = 1602,
  ["repo"] = "cosmic-lua/cosmic",
  ["resolution"] = "completed",
  ["speccers"] = "d6d4a5ca-5feb-579c-b294-e39c72bf3099",
  ["title"] = "sandbox.merge() silently drops the net and scope sections from its result",
  ["verdict"] = "accept",
  ["verdict_head"] = "611f91e4cb348bac3b9f7e7d8ba74446ee8c0d14",
  ["verdict_spec"] = "cd212a14cac98a25f3f9fd00c02c9f2d98473976ad21651a6e59f45e3e1f0621",
}
