return {
  ["builders"] = "c3166793-5886-5fa0-8f44-66f7df2ae6f2 builder-sYEp_31Y1-orch9 orchestrate9-sYEp_31Y1 7019a67a-89f8-5ed7-bd1c-6d260093b01b",
  ["id"] = "3IlL8oOGolatj0YHGHWsYEp31Y1",
  ["parent"] = "3HyRdY4sPAYZ6xkwrXCh5BnsH7B",
  ["repo"] = "cosmic-lua/cosmic",
  ["resolution"] = "completed",
  ["speccers"] = "orchestrate9-sYEp_31Y1 7019a67a-89f8-5ed7-bd1c-6d260093b01b",
  ["title"] = "decision: how a SQLite BLOB is told from TEXT at the Lua boundary (representation and scope) for lsqlite3",
}
