return {
  ["builders"] = "wave6-lok152-c1",
  ["id"] = "3IlWPkpc0kWTgZd9z2F1IGbL4mM",
  ["parent"] = "3IQfJ1tnwZOiJrWvDOgIxsjLrBt",
  ["pr"] = 1632,
  ["repo"] = "cosmic-lua/cosmic",
  ["resolution"] = "completed",
  ["title"] = "check.must sweep: cosmic/fs/** — 10 sites in 4 files",
  ["verdict"] = "accept",
  ["verdict_head"] = "9eae93881e420752137427f52aeb183e9b851d08",
  ["verdict_spec"] = "c31b1cd5393fa55db592ed1d1ca80328fc9e951318efec5fcca95316bea44c89",
}
