return {
  ["builders"] = "1d4829cc-f00e-5d15-be81-281e86c6c454",
  ["id"] = "3Im3EEyh1grgpqQiD5UVxfeYoE3",
  ["parent"] = "3IOCIBGeYoISEhI0VJPwZmqduSZ",
  ["repo"] = "cosmic-lua/cosmic",
  ["resolution"] = "completed",
  ["result"] = "db9f0de51e85398f12475653369c8d612c4724a86c303e0011b3d56a0d3d1f16",
  ["speccers"] = "1d4829cc-f00e-5d15-be81-281e86c6c454",
  ["title"] = "does testrun_dep already invalidate spawned-binary tests on an engine rebuild, making the per-file reads: o/bin/cosmic declaration redundant?",
  ["verdict"] = "accept",
  ["verdict_spec"] = "db9f0de51e85398f12475653369c8d612c4724a86c303e0011b3d56a0d3d1f16",
}
