return {
  ["builders"] = "builder-rHCW_59sk-orch9 7019a67a-89f8-5ed7-bd1c-6d260093b01b",
  ["id"] = "3ImmKYCJNNxTS9eAISxrHCW59sk",
  ["parent"] = "3IPXQ1Zw1xfRYx4dV1zwASNhQ3N",
  ["repo"] = "cosmic-lua/cosmic",
  ["resolution"] = "completed",
  ["speccers"] = "7019a67a-89f8-5ed7-bd1c-6d260093b01b",
  ["title"] = "decision: can FileIter/LineIter/Body.lines be honestly retyped non-nilable, given a documented direct-call terminating-payload read outside for-in?",
}
