return {
  ["base"] = "main",
  ["builders"] = "build-sWmK_pFNW-41598fb4",
  ["id"] = "3Iqz0MKivJMoWrGrPU0sWmKpFNW",
  ["parent"] = "3HyRdT1JQS7pCPgF3sZi2Deo66q",
  ["pr"] = 1696,
  ["repo"] = "cosmic-lua/work",
  ["resolution"] = "completed",
  ["title"] = "gitboard next: wire live CI state into action.tl's already-correct running/red skip",
  ["verdict"] = "accept",
  ["verdict_head"] = "0f99726aa3fbf64815f568988166eaf38f7348ce",
  ["verdict_spec"] = "d75558f6ea019adacac56aa9fff431285d9a1522a220be753929460a6546e759",
}
