return {
  ["builders"] = "9e51ea3a-3544-5795-b441-cd8aba4b7aee 0b13d2b4-bb26-5bc1-8635-407acd85452c",
  ["id"] = "3IVHXoDwkRfFIJIvCVCDA4mCpTi",
  ["parent"] = "3IODJgkObjfhsxqMPEgFPIM6RHR",
  ["pr"] = 1471,
  ["repo"] = "cosmic-lua/cosmic",
  ["resolution"] = "completed",
  ["title"] = "the checker accepts return nil from a bare non-nil declared return, so an annotation can lie and no nil tool fires",
}
